# Generated by Django 3.0.5 on 2020-04-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=30)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('book_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookStore')),
            ],
            bases=('core.basemodel',),
        ),
    ]
